### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by akanesra** [patrickvonplaten/AdvertisementDetection#2]
While running **./createFramesFromMultipleVideos.sh 0.8 0.55 0.6**, I got these errors:

./createFramesFromMultipleVideos.sh: line 39: 00008: value too great for base (error token is "00008")
./createFramesFromMultipleVideos.sh: line 39: 00009: value too great for base (error token is "00009")
...
./createFramesFromMultipleVideos.sh: line 53: 00008: value too great for base (error token is "00008")
./createFramesFromMultipleVideos.sh: line 53: 00009: value too great for base (error token is "00009")
...

As a result, only 690 images are generated instead of 1016. Some indices are skipped as well, making the last index 734.

**Comment by patrickvonplaten** [comment]
solved -> try again, it should work now
